var frutas = ["Banana", "Maçã", "Pêra", "Uva", "Morango"];
console.log(frutas);
console.log(frutas[0]);
console.log("--------------------------------");
console.table(frutas);
console.log("--------------------------------");
frutas.push("Tangerina");
console.table(frutas);
console.log("--------------------------------");
frutas.unshift("Goiaba");
console.table(frutas);
console.log("--------------------------------");
//var elementoProcurado = "Morango";
//var posicao = frutas.indexOf(elementoProcurado);
//console.log("O " + elementoProcurado + " está no índice " + posicao);
console.log(frutas[5]);
console.log("---------------------------------");
//frutas.splice(4, 1);
var pos = frutas.indexOf("Uva");
frutas.splice(pos, 1);
console.table(frutas);
console.log("----------------------------------");
var copia = frutas.slice(2, 5);
console.table(copia);

var number = [1, 2, 3, 4, 5];
console.table(number);
console.log("-------------------------");
console.log("A terceira posição possui o valor", number[2]);
console.log("");
console.log("");
var copy1 = number.slice();
console.table(copy1);
console.log("");
console.log("");
copy1[0] = number[0] * 2;
copy1[1] = number[1] * 2;
copy1[2] = number[2] * 2;
copy1[3] = number[3] * 2;
copy1[4] = number[4] * 2;
console.table(copy1);